version: 

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "10000:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpass
      - WEBHOOK_TUNNEL_URL=
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - TZ=Europe/Cairo
    volumes:
      - ~/.n8n:/home/node/.n8n
